version: "3"

dotenv:
  - .env.local

tasks:
  default:
    desc: Run service locally
    cmds:
      - task: run

  run:
    desc: Start service locally
    cmds:
      - echo "Starting service locally..."
      - go run ./cmd/api/main.go

  docker-build:
    desc: Build docker image
    cmds:
      - docker build -t ts-backend:latest .

  docker-start:
    desc: Start docker container
    cmds:
      - docker run -d --env-file .env -p 8080:8080 ts-backend:latest
